// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRo9z2mgIIHKJjO5q_Zm4TGwYLvOG3bME',
    appId: '1:983680612548:web:4967fb1b3e1967060f7191',
    messagingSenderId: '983680612548',
    projectId: 'insta-clone-without-users',
    authDomain: 'insta-clone-without-users.firebaseapp.com',
    storageBucket: 'insta-clone-without-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxBxQcCYEKPDZ6UqIdAc6HbfACU0_rGbw',
    appId: '1:983680612548:android:0ff70ef4c7dbde6a0f7191',
    messagingSenderId: '983680612548',
    projectId: 'insta-clone-without-users',
    storageBucket: 'insta-clone-without-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc94yzgvdda2oUL7KV4vA3Aa5ZhSDHh58',
    appId: '1:983680612548:ios:311769e055460dc80f7191',
    messagingSenderId: '983680612548',
    projectId: 'insta-clone-without-users',
    storageBucket: 'insta-clone-without-users.appspot.com',
    iosClientId: '983680612548-7obeas0995hvsdf4rkf54a44vrootpuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc94yzgvdda2oUL7KV4vA3Aa5ZhSDHh58',
    appId: '1:983680612548:ios:40ae4a51c9db06970f7191',
    messagingSenderId: '983680612548',
    projectId: 'insta-clone-without-users',
    storageBucket: 'insta-clone-without-users.appspot.com',
    iosClientId: '983680612548-62h5ah4lc4bac8qn5v0c77dk4uu9878a.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
